# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
