# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_plan_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='owner',
        ),
    ]
